### ISSUE TITLE
[BetterStats] Bug with display/sec option with thousands number using "dot" separator

### ISSUE THREAD

**Issue by Chrisalead** [DysonSphereMod/QOL#100]
Hi, in last version there is a small but still annoying bug creating an assert window. If a resource is in the thousands but with a "." as decimal separator instead of "," then the assert occurs when trying to use the "display/sec" option.

for instance :

846,5 will work and goes to 14,11

but 10.6k will create the assert. (ReverseFormat fonction call fails)

**Comment by Chrisalead** [comment]
No news for that bug ?

**Comment by ThomasBlt** [comment]
@Chrisalead I've wrote what I supposed to be a bugfix for this in #101 
Unfortunately I'm not a c# developer and I wasn't able to find how to compile and then test this. I hope someone could do it for me or point me out a working tuto for me to be able to do it by myself.

**Comment by starfi5h** [comment]
![betterstats](https://user-images.githubusercontent.com/50672801/124860656-962cfb80-dfe4-11eb-971c-c7475b5c713c.jpg)
I build a temporary fix for the latest game version. Can you check whether the problem is solved?  
[https://github.com/starfi5h/QOL/releases/tag/BetterStats%401.2.1](https://github.com/starfi5h/QOL/releases/tag/BetterStats%401.2.1)
