### ISSUE TITLE
[RailgunsRetargeting] Error when loading a save

### ISSUE THREAD

**Issue by Veretragna** [DysonSphereMod/QOL#115]
![2021-07-31_154350](https://user-images.githubusercontent.com/14805612/127740277-8f465d50-8c94-46dc-81ab-5f16062f8fc6.jpg)

**Comment by Veretragna** [comment]
Yesterday it worked just fine, today it doesn't. This error appears randomly.

**Comment by Veretragna** [comment]
Tried to load all autosaves, nothing works.

**Comment by nyqeest** [comment]
same problem here

**Comment by nyqeest** [comment]
hello, i found such a fix for this mod, but i don't know how to use it, could someone advise me?
https://github.com/starfi5h/QOL/commit/f4040a37def393ab319130a01311071fe23c137c

**Comment by Veretragna** [comment]
Good news: I found a temporary workaround. I disabled the mod and all railguns, waited till all solar sails absorbed, and re-enabled the save.
Bad news: this mod broke my savefile. Unfortunately I don't have the screenshot, but error screen shown something like "RailgunsRetargeting LateUpdate" event directly after save.

**Comment by gyathaar** [comment]
I got bug similar also (didnt save screenshot so not 100% sure if the same one) .. disabled mod.. and noticed one of the railguns had no orbit set.. saved and loaded with mod.. and all was working fine again

**Comment by Daedeross** [comment]
The mod uses a non thread-safe Dictionary to store some state which has been causing this issue since the 0.7.x update to DSP, which added multi-threading. There is a pending Pull Request  ( #112 ) which will fix it.

**Comment by nyqeest** [comment]
@Daedeross yes, but sorry for noob question, but can you explain how to use this fix? I use thunderstorm to install mods into game, and in plugin folder i have only .dll file

**Comment by Daedeross** [comment]
@nyqeest Until the PR is merged and a new version is released on Thunderstore by the author, you will have to build and apply the mod yourself. If you need a primer on doing that, check out [this page in the wiki](https://dsp-wiki.com/Modding:Modding). The [Getting Started](https://dsp-wiki.com/Modding:Getting_Started) article goes over how to manually install the mod.
To get the code, you need to download or clone the PR's branch `git clone https://github.com/starfi5h/QOL.git`.
[This Steam Guide](https://steamcommunity.com/sharedfiles/filedetails/?id=2106187116) shows what you need to do to build a mod in Visual Studio (Note, wherever it says "Streets of Rogue" just insert "Dyson Sphere Program") . You mostly only need to read through step 2 & 3 since the rest has already been done.

**Comment by burdoto** [comment]
Closed by #111 and #112

**Comment by nyqeest** [comment]
@Daedeross @burdoto Thank you guys very much, I tried to compile it myself and even got a dll but unfortunately it didn't work. For me, this mod is basic to the sail shooting system, especially for larger builds. Thank you again, stay efficient :)

**Comment by brokenmass** [comment]
fixed in 1.3.3
