### ISSUE TITLE
How to install in DSP?

### ISSUE THREAD

**Issue by reinaldorauch** [DysonSphereMod/QOL#4]
I've tried running it with [r2modmanPlus](https://github.com/ebkr/r2modmanPlus)

But it seems to be not registering with the game. How i can launch it with the mod?

**Comment by kyldvs** [comment]
I haven't had issues with r2modmanPlus. Some things that might fix the issues:

- Make sure "BepInEx" plugin is installed. All plugins require this.
- Click "online" and search for "brokenmass" to list the plugins from this repo, then click "download" on the ones you want
- Close Dyson Sphere Program and then from within r2modmanPlus click "Start modded" in order to launch the game with all the  mods you've downloaded enabled

**Comment by brokenmass** [comment]
thanks  @kyldvs  for the clear explanation

**Comment by reinaldorauch** [comment]
@kyldvs i will try later, thanks

**Comment by reinaldorauch** [comment]
It worked when launching from r2modmanplus but when i launched with steam it didnt get it, even with the startup option added. What can I do?

**Comment by kyldvs** [comment]
That is intended, it's expected for you to launch through r2modmanPlus in order to have access to the mods. If you would like to be able to launch through steam you need to manually install the mods by manually downloading, extracting the zip files, and placing the .dll files into: `...steamapps\common\Dyson Sphere Program\BepInEx\plugins`

**Comment by reinaldorauch** [comment]
@kyldvs thanks :D
